### PR TITLE
Add feat switch the less version on less-preview

### PR DESCRIPTION
**Pull request by lumburr**
eg: https://stackblitz.com/edit/nuxt-starter-zbg7ab?file=README.md,nuxt.config.js
After the function is complete, three problems are found:
1. The version 3.12.1-alpha.13 is changed, but the window.less version is 4.0. This is a historical reason.
2. If you switch to 2.6.1 or 2.6.0, a white screen is displayed.
3. 2.4.0 and earlier versions cannot be loaded through the CDN. Should we remove it?

### CODE REVIEW

**Comment by iChenLei** [comment]
Coooooool

**Review by iChenLei — COMMENTED** [review]
1.  small screen ui crash


2.  can you add a hint toast for less switch sucess or fail ? 

Anyway, thanks for your contribution.

**Comment by iChenLei** [comment]
@lumburr  https://github.com/lumburr/less-preview/tree/refactor Great job !

**Comment by iChenLei** [comment]
@lumburr So did you finish your work for new `less-preview` ? We don't need 100% perfect `less-preview`, maybe release a available version is a good choice, and then keep iterating. What't your opinion ?

**Comment by lumburr** [comment]
> @lumburr那么你完成了新的工作`less-preview`吗？我们不需要 100% 完美`less-preview`，也许发布一个可用的版本是一个不错的选择，然后继续迭代。你有什么意见？

@iChenLei  Yes you're right, we should provide a usable version first. Could you please look at https://github.com/less/less-preview/pull/11 ?

**Pull request closed without merging**
